version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: ./apps/myapp/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./apps/myapp:/app
      - ./dist/apps/myapp:/app/dist
      - ./apps/myapp/src/.env:/app/.env
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - /app/node_modules
    environment:
      NODE_ENV: development
      DOCKER_ENV: true
    command: 'nodemon dist/src/main.js'
