version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: ./apps/myapp/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/workspace
    # working_dir: /workspace/apps/myapp
    environment:
      NODE_ENV: development
      DOCKER_ENV: true
    # command: 'nodemon dist/src/main.js'
    command: tail -f /dev/null

  first-monorepo:
    build:
      context: .
      dockerfile: ./apps/first-monorepo/Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - .:/workspace
    working_dir: /workspace/apps/first-monorepo
    environment:
      NODE_ENV: development
      DOCKER_ENV: true
    command: 'nodemon dist/src/main.js'
