name: Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow access to repository contents
      packages: write # Allow publishing to GitHub Packages
      id-token: write # Needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit message format
        id: check_message
        run: |
          if [[ ! "${{ github.event.head_commit.message }}" =~ ^[a-z]+\([a-zA-Z0-9_-]+\):\ .+ ]]; then
            echo "Commit message format is invalid."
            exit 1
          fi

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Set Git user
        run: |
          git config --global user.name "${{ github.actor }}"

      - name: Bump version & Publish packages
        run: make release EXEC=true
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_ACCESS: public

      - name: Push bump & tag
        run: git push origin main && git push origin --tags
        shell: bash
